### ISSUE TITLE
自定义规则无法过滤广告

### ISSUE THREAD

**Issue by ITdesk01** [project-lede/luci-app-godproxy#11]
广告图片如下
![image](https://user-images.githubusercontent.com/38835844/110582509-47429700-81a7-11eb-8f23-03c8be61439a.png)

自定义规则如下（两条我都试过，就是无法过滤掉广告图片，求解）
                        
                   https://www.right.com.cn/forum/static/image/common/logo1.gif
                   ||right.com.cn/forum/static/image/common/logo1.gif

**Comment by ihuaer** [comment]
https需要安装证书

**Comment by ITdesk01** [comment]
> https需要安装证书

懂你意思了。我知道了，谢谢，确实可以了
