### ISSUE TITLE
打开谷歌提示“您的连接不是私密连接”

### ISSUE THREAD

**Issue by ssdsl0126** [project-lede/luci-app-godproxy#13]
如题，已经更新过规则了
![image](https://user-images.githubusercontent.com/35905829/111171549-ffc16e00-85df-11eb-941d-7f4aaa014114.png)

**Comment by ssdsl0126** [comment]
只打开视频规则也是这样

**Comment by project-lede** [comment]
HTTPs
证书没有安装
