### ISSUE TITLE
Fanboy规则+HTTPS過濾和line衝突

### ISSUE THREAD

**Issue by IthildinX** [project-lede/luci-app-godproxy#14]
手機設置HTTPS過濾並訂閱fanboy規則後，line會無法使用
加上以下白名單後，對話恢復正常，但是無法收發照片，也無法打開貼圖小舖

line.naver.jp
line-apps.com
line-scdn.net
line.me

想詢問一下有沒有除了取消訂閱Fanboy規則以外的解決辦法?

**Comment by project-lede** [comment]
目前没有
