### ISSUE TITLE
启用后小米手机链接提示开放网络

### ISSUE THREAD

**Issue by tzxiaozhen88** [project-lede/luci-app-godproxy#21]
启用后小米手机链接提示开放网络，x64软路由下面2 ap

**Comment by xiaoqi2020** [comment]
> 启用后小米手机链接提示开放网络，x64软路由下面2 ap

我还以为是路由器的问题，我也有这个提示！

**Comment by tzxiaozhen88** [comment]
> > 启用后小米手机链接提示开放网络，x64软路由下面2 apAfter enabling Xiaomi Mobile Link Prompt Open Network, x64 soft route below 2AP
> 
> 我还以为是路由器的问题，我也有这个提示！
> 
> I thought it was the router. I had the same clue!
但是笔记本和三星手机，电视机多没问题 不知道这么回事

**Comment by michealhansun** [comment]
之前我也有，我不勾选自定义规则就没有这个提示了
