### ISSUE TITLE
希望添加新规则

### ISSUE THREAD

**Issue by tjr57** [project-lede/luci-app-godproxy#24]
强烈希望添加这三个源：
https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

另外建议abp规则替换为Halflife-pc：
https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-pc.txt

**Comment by Karmylr** [comment]
想多了 估计都不会转换规则

**Comment by project-lede** [comment]
经多次测试，建议的规则斗不能转化成kolproxy'可识别的规则。
