### ISSUE TITLE
开启插件连接wifi就会提示（需登陆/认证）

### ISSUE THREAD

**Issue by svipkid** [project-lede/luci-app-godproxy#25]
XJ3160刷的op，只要启动插件，每次从外面回家，连接wifi就会提示（需登陆/认证）！不知道是插件原因，还是规则原因！
只要关掉插件就正常连接！！每次连接wifi，都需要点击√，认证后才能联网！

**Comment by michealhansun** [comment]
自定义规则有问题，取消就正常了，具体哪个规则的问题就需要大佬查看了

**Comment by db-one** [comment]
是小米的这个域名
connect.rom.miui.com
被干掉就会提示需要认证

**Comment by project-lede** [comment]
添加到白名单即可。或者升级到最新版
