### ISSUE TITLE
开启godproxy之后，开启https后passwall流量会锁定在3m/s以下

### ISSUE THREAD

**Issue by chenmoyua** [project-lede/luci-app-godproxy#28]
开启godproxy，开启https过滤后passwall出国访问网站看视频流量会锁定在3m/s以下，而使用测速软件就不会限速。其他代理软件就没有这个问题。关掉godproxy或者只开启http过滤后，passwall出国恢复正常，看视频也不会限速了

**Comment by tjr57** [comment]
我也遇到了

**Comment by zack-112** [comment]
装两个op 一个出国，一个去广告，就能解决这个问题

**Comment by pigpigabc123** [comment]
> 装两个op 一个出国，一个去广告，就能解决这个问题

串联吗？我的理解是从内网向外网看，广告在前，留学在后

**Comment by zack-112** [comment]
具体不清楚，但是在同一个op上跑就出问题

发自我的iPhone
