### ISSUE TITLE
最新编译，无法访问百度首页

### ISSUE THREAD

**Issue by xylz0928** [project-lede/luci-app-godproxy#29]
https已启用，iOS14.5，证书已装已信任。
百度网盘能打开，百度首页打不开，加载到一半，
如何排查？

**Comment by Arthur2012** [comment]
同样的问题，很奇怪。把baidu.com加入白名单也不行。
这个问题只针对装了证书的设备，开启https过滤就会导致这个问题。
未装证书的其它设备打开百度网页正常。
