### ISSUE TITLE
cpu 内存 占用过高的问题

### ISSUE THREAD

**Issue by RuningBun** [project-lede/luci-app-godproxy#30]
正常开启 之后 top命令查看 占用情况
**27430     1 root     S    1812m  46%  92% /usr/share/koolproxy/koolproxy --mark --ttl 160 --ipv6**
内存占用 46% cpu 92%
设备 cpu 为 x86 i5-4590 分配openwrt 2核 4G内存。

**Comment by Nicepaul** [comment]
确实有这个问题，这个问题在KoolProxyR 3.8.4时就有，应该是历史遗留问题
