### ISSUE TITLE
和shadowsocks plus+ 冲突，开启后导致国外可以访问，国能网页统统打不开，关闭去广告或者ssrplus+国内访问恢复正常。

### ISSUE THREAD

**Issue by fanrongboy** [project-lede/luci-app-godproxy#31]
![image](https://user-images.githubusercontent.com/26063705/118830386-7a18b200-b8f1-11eb-8125-12c70707ebc0.png)

**Comment by jkle112** [comment]
请问你是不是用的从koolshare.cn上下载的固件，尤其是华硕改版过来的，我之前也碰到这种情况，现在用软路由，发现没问题
