### ISSUE TITLE
太占资源了，动不动就卡CPU到100%

### ISSUE THREAD

**Issue by o-00-o** [project-lede/luci-app-godproxy#32]
N1刷的OpenWrt，GodProxy插件3.8.5版本，默认访问控制选择不过滤，只指向了一个电视盒子做过滤。
但在盒子未通电，内网几乎没有活动网络设备的情况下，居然N1软路由的CPU莫名其妙跑到100%。
观察了好几天，卡CPU也不是一直卡，突然毫无征兆的卡了，卡个十几分钟，恢复正常，过段时间又突然卡。
卡CPU时，查看进程，发现就是KoolProxyR Plus的进程在疯跑。

折腾了好几天了，设置上想尽了办法，还是会卡CPU，实在没辙，先关闭插件了。等大佬的更新。

**Comment by Karmylr** [comment]
n1性能本来就不够。

**Comment by ihuaer** [comment]
> N1刷的OpenWrt，GodProxy插件3.8.5版本，默认访问控制选择不过滤，只指向了一个电视盒子做过滤。
> 但在盒子未通电，内网几乎没有活动网络设备的情况下，居然N1软路由的CPU莫名其妙跑到100%。
> 观察了好几天，卡CPU也不是一直卡，突然毫无征兆的卡了，卡个十几分钟，恢复正常，过段时间又突然卡。
> 卡CPU时，查看进程，发现就是KoolProxyR Plus的进程在疯跑。
> 
> 折腾了好几天了，设置上想尽了办法，还是会卡CPU，实在没辙，先关闭插件了。等大佬的更新。

你看看系统日志  
里面有错误信息的

openwrt系统异常或者过滤规则不规范会导致CPU 100%

一般N1跑KOOLPROXY 占用20%左右
- 

1.  #@
![FastStoneEditor1](https://user-images.githubusercontent.com/12723080/120600383-4a35e680-c47b-11eb-95c8-7d1b363e3e60.jpg)



> 

>

**Comment by o-00-o** [comment]
> > N1刷的OpenWrt，GodProxy插件3.8.5版本，默认访问控制选择不过滤，只指向了一个电视盒子做过滤。
> > 但在盒子未通电，内网几乎没有活动网络设备的情况下，居然N1软路由的CPU莫名其妙跑到100%。
> > 观察了好几天，卡CPU也不是一直卡，突然毫无征兆的卡了，卡个十几分钟，恢复正常，过段时间又突然卡。
> > 卡CPU时，查看进程，发现就是KoolProxyR Plus的进程在疯跑。In the N1 brush version of OpenWrt, GodProxy 3.8.5, the default access control option does not filter, but only points to a TV box for filtering. But in the box is not powered, the internal network almost no active network equipment circumstances, unexpectedly N1 soft route CPU inexplicably ran to 100% . Observed for several days, the card CPU is not a card, suddenly without any warning card, card for more than ten minutes, back to normal, after a period of time and suddenly card. Card CPU, check the process, found that is the process Koolproxyr Plus crazy running.
> > 折腾了好几天了，设置上想尽了办法，还是会卡CPU，实在没辙，先关闭插件了。等大佬的更新。Toss for a few days, set up all the way, or card CPU, really no way, first off the plug-in. Waiting for updates from the movers and shakers.
> 
> 你看看系统日志
> 里面有错误信息的
> 
> Look at the system log. There’s an error message
> 
> openwrt系统异常或者过滤规则不规范会导致CPU 100%
> 
> Open WRT system exceptions or irregular filtering rules can result in 100% CPU
> 
> ## 一般N1跑KOOLPROXY 占用20%左右
> ## General N 1 run KOOLPROXY occupy about 20%
> 1. #@
>    ![FastStoneEditor1](https://user-images.githubusercontent.com/12723080/120600383-4a35e680-c47b-11eb-95c8-7d1b363e3e60.jpg)
> 
> > 
> 
> >

感谢您的回复！
我用的是F大的OP固件58+o。参考你说的规则冲突一说，又尝试了各种设置，问题依旧存在。
倒也不是一直CPU卡100%，大概半小时~一小时吧，会卡一次，一次持续10分钟左右。
保存GodProxy的设置，插件重启，可以恢复正常，但过一会又开始卡。
系统日志里，没有记录。GodProxy只有更新日志，没有运行日志，查不到问题在哪。
无奈，实在没招，关闭了插件，改用广告屏蔽大师 Plus+，暂时先用着。

**Comment by ihuaer** [comment]
> > > N1刷的OpenWrt，![image](https://user-images.githubusercontent.com/12723080/120736903-b10cdb80-c51f-11eb-84eb-9c21bf028198.png)插件3.8.5版本，默认访问控制选择不过滤，只指向了一个电视盒子做过滤。
> > > 但在盒子未通电，内网几乎没有活动网络设备的情况下，居然N1软路由的CPU莫名其妙跑到100%。
> > > 观察了好几天，卡CPU也不是一直卡，突然毫无征兆的卡了，卡个十几分钟，恢复正常，过段时间又突然卡。
> > > 卡CPU时，查看进程，发现就是KoolProxyR Plus的进程在疯跑。In the N1 brush version of OpenWrt, GodProxy 3.8.5, the default access control option does not filter, but only points to a TV box for filtering. But in the box is not powered, the internal network almost no active network equipment circumstances, unexpectedly N1 soft route CPU inexplicably ran to 100% . Observed for several days, the card CPU is not a card, suddenly without any warning card, card for more than ten minutes, back to normal, after a period of time and suddenly card. Card CPU, check the process, found that is the process Koolproxyr Plus crazy running.
> > > 折腾了好几天了，设置上想尽了办法，还是会卡CPU，实在没辙，先关闭插件了。等大佬的更新。Toss for a few days, set up all the way, or card CPU, really no way, first off the plug-in. Waiting for updates from the movers and shakers.
> > 
> > 
> > 你看看系统日志
> > 里面有错误信息的
> > Look at the system log. There’s an error message
> > openwrt系统异常或者过滤规则不规范会导致CPU 100%
> > Open WRT system exceptions or irregular filtering rules can result in 100% CPU
> > ## 一般N1跑KOOLPROXY 占用20%左右
> > ## General N 1 run KOOLPROXY occupy about 20%
> > 
> > 1. #@
> >    ![FastStoneEditor1](https://user-images.githubusercontent.com/12723080/120600383-4a35e680-c47b-11eb-95c8-7d1b363e3e60.jpg)
> > 
> > > 
> > 
> > 
> > >
> 
> 感谢您的回复！
> 我用的是F大的OP固件58+o。参考你说的规则冲突一说，又尝试了各种设置，问题依旧存在。
> 倒也不是一直CPU卡100%，大概半小时~一小时吧，会卡一次，一次持续10分钟左右。
> 保存GodProxy的设置，插件重启，可以恢复正常，但过一会又开始卡。
> 系统日志里，没有记录。GodProxy只有更新日志，没有运行日志，查不到问题在哪。
> 无奈，实在没招，关闭了插件，改用广告屏蔽大师 Plus+，暂时先用着。

在openwrt-系统日志-这里可以查看GodProxy异常

一般情况下N1运行KP会占用20%左右的CPU
