### ISSUE TITLE
大雕新版源码，开启规则就崩！~

### ISSUE THREAD

**Issue by brianzc0306** [project-lede/luci-app-godproxy#35]
大雕新版源码，开启规则就崩！~
Thu Jun 17 15:36:02 2021 kern.info kernel: [  219.840140] koolproxy[6706]: segfault at 7fa1e4134900 ip 00007fa1e4134900 sp 00007fa1e4134898 error 15
Thu Jun 17 15:36:02 2021 kern.info kernel: [  219.842895] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 80 e0 a1 7f 00 00 41 bb 30 2f 41 00 49 ba e0 48 13 e4 a1 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 48 13 e4 a1 7f 00 00 49 ff e3 90 a1 7f
Thu Jun 17 15:36:07 2021 daemon.info koolproxy[7235]: koolproxy v3.8.5
Thu Jun 17 15:36:08 2021 kern.info kernel: [  226.260971] koolproxy[7239]: segfault at 7f3155264900 ip 00007f3155264900 sp 00007f3155264898 error 15
Thu Jun 17 15:36:08 2021 kern.info kernel: [  226.263707] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 80 51 31 7f 00 00 41 bb 30 2f 41 00 49 ba e0 48 26 55 31 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 48 26 55 31 7f 00 00 49 ff e3 90 31 7f
Thu Jun 17 15:36:13 2021 daemon.info koolproxy[7254]: koolproxy v3.8.5
Thu Jun 17 15:36:14 2021 kern.info kernel: [  232.287656] koolproxy[7263]: segfault at 7f86db765900 ip 00007f86db765900 sp 00007f86db765898 error 15
Thu Jun 17 15:36:14 2021 kern.info kernel: [  232.291114] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 e0 d7 86 7f 00 00 41 bb 30 2f 41 00 49 ba e0 58 76 db 86 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 58 76 db 86 7f 00 00 49 ff e3 90 86 7f
Thu Jun 17 15:36:14 2021 kern.info kernel: [  232.291131] koolproxy[7262]: segfault at 7f86db790900 ip 00007f86db790900 sp 00007f86db790898 error 15
Thu Jun 17 15:36:14 2021 kern.info kernel: [  232.299298] Code: 00 00 95 34 41 00 00 00 00 00 d8 d7 e0 d7 86 7f 00 00 41 bb 30 2f 41 00 49 ba e0 08 79 db 86 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 08 79 db 86 7f 00 00 49 ff e3 90 86 7f
Thu Jun 17 15:36:19 2021 daemon.info koolproxy[7273]: koolproxy v3.8.5
Thu Jun 17 15:36:20 2021 kern.info kernel: [  238.465245] koolproxy[7282]: segfault at 7efff54fc900 ip 00007efff54fc900 sp 00007efff54fc898 error 15
Thu Jun 17 15:36:20 2021 kern.info kernel: [  238.467926] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 c0 f1 ff 7e 00 00 41 bb 30 2f 41 00 49 ba e0 c8 4f f5 ff 7e 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 c8 4f f5 ff 7e 00 00 49 ff e3 90 ff 7e
Thu Jun 17 15:36:25 2021 daemon.info koolproxy[7292]: koolproxy v3.8.5
Thu Jun 17 15:36:26 2021 kern.info kernel: [  244.433087] koolproxy[7303]: segfault at 7faa46146900 ip 00007faa46146900 sp 00007faa46146898 error 15
Thu Jun 17 15:36:26 2021 kern.info kernel: [  244.435794] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 80 42 aa 7f 00 00 41 bb 30 2f 41 00 49 ba e0 68 14 46 aa 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 68 14 46 aa 7f 00 00 49 ff e3 90 aa 7f
Thu Jun 17 15:36:31 2021 daemon.info koolproxy[7313]: koolproxy v3.8.5
Thu Jun 17 15:36:32 2021 kern.info kernel: [  250.334192] koolproxy[7322]: segfault at 7f0387b4c900 ip 00007f0387b4c900 sp 00007f0387b4c898 error 15
Thu Jun 17 15:36:32 2021 kern.info kernel: [  250.336928] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 20 84 03 7f 00 00 41 bb 30 2f 41 00 49 ba e0 c8 b4 87 03 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 c8 b4 87 03 7f 00 00 49 ff e3 90 03 7f
Thu Jun 17 15:36:32 2021 daemon.info procd: Instance koolproxy::instance1 s in a crash loop 6 crashes, 1 seconds since last crash

**Comment by CJLUGaoXinyu** [comment]
俺也一样

**Comment by saoba1982** [comment]
我也是，如何解决？

**Comment by tx6188** [comment]
同样问题，求解决

**Comment by nnttm1122** [comment]
同样问题，希望尽快解决

**Comment by jimgo188** [comment]
可能不支持新内核，我是开启一直重启

**Comment by saoba1982** [comment]
内核改回5.4就可以了

**Comment by ihuaer** [comment]
内核改回5.4

**Comment by Portan** [comment]
> 内核改回5.4就可以了

请问怎么改回5.4内核？

**Comment by project-lede** [comment]
猴子大大的规则内容已经为空了。所以无法识别。已经修复，直接后台更新即可。最近实在忙，抱歉。
