### ISSUE TITLE
5.10内核下，会停止运行

### ISSUE THREAD

**Issue by WXfeng-boy** [project-lede/luci-app-godproxy#36]
不知大佬能不能修复下，感谢

**Comment by saoba1982** [comment]
大佬快来帮忙修复一下5.10内核无法启动的问题吧.

**Comment by duxiangjiang** [comment]
我也遇到了同样的问题

**Comment by jimgo188** [comment]
还不支持5.10内核 ，希望能升级下，我为了这个去广告编译都没用5.10内核，这个是硬需啊，主要是去电视视频广告方便。

**Comment by michealhansun** [comment]
今天编译L大最新的5.10.51，我的也是运行不了了。。。

**Comment by project-lede** [comment]
猴子大大的规则内容已经为空了。所以无法识别。已经修复，直接后台更新即可。最近实在忙，抱歉。
