### ISSUE TITLE
网站白名单设置、端口控制开关 无法保存应用问题

### ISSUE THREAD

**Issue by shangxin-lazy** [project-lede/luci-app-godproxy#37]
不知道是什么原因，用了两个不同的固件（小鸡过河和esir的固件）

esir的固件（包括高大全和精品小包）以及小鸡过河的固件中，godproxy网站白名单设置：输入设置的内容后，保存并应用正常，再删除规则（全部都删除），会出现无法保存的情况（点击保存并应用，不出现保存倒计时，直接刷新了，而且没有保存），但是可以空格再保存并应用，就正常了，不知道这个是bug还是什么呢

端口控制也差不多，无法保存

**Comment by shangxin-lazy** [comment]
哦对，小鸡过河的固件中，是5.10的内核版本，会出现godproxy一会运行，一会停止运行的情况

**Comment by ihuaer** [comment]
> 哦对，小鸡过河的固件中，是5.10的内核版本，会出现godproxy一会运行，一会停止运行的情况

5.10内核不兼容

**Comment by project-lede** [comment]
升级到新版试试
