### ISSUE TITLE
在Ipad上无法去除YouTube广告

### ISSUE THREAD

**Issue by duxiangjiang** [project-lede/luci-app-godproxy#38]
在Ipad上装好了证书，其它广告都能去，就是怎么都去不了YouTube的广告，请问是规则的问题吗？如果自己加入第三方规则就会反复的停止运行，实在是没办法了，请大家指点一下，不甚感激。

**Comment by ihuaer** [comment]
规则问题，添加新规则

**Comment by Karmylr** [comment]
godproxy这个项目完了。本来就是koolproxyr换皮。koolproxyr停更了，godproxy是绝对没有办法做下去的。规则会慢慢的是小。会出现一些理由来停止更新godproxy

**Comment by project-lede** [comment]
重新更新规则。一定要使用最新版
