### ISSUE TITLE
大佬使用godproxy后发现和翻墙软件冲突能帮忙适配一下吗？

### ISSUE THREAD

**Issue by zack-112** [project-lede/luci-app-godproxy#4]
使用godproxy和翻墙软件后，会导致开启去广告的设备突然没有网络，视频网站都无法打开，关掉翻墙软件后就没问题，使用的翻墙软件为ShadowSocksR Plus+，Hello World，这些都不行。

**Comment by project-lede** [comment]
仔细研读 https://github.com/project-lede/luci-app-godproxy/blob/main/about-koolproxy.txt
