### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by jkle112** [project-lede/luci-app-godproxy#41]
内核5.4.132，添加规则后，内存消耗特别大，自动更新规则后，完全停止运行，希望能解决！
日志项目是空白的

**Comment by jimgo188** [comment]
不能运行是更新视频规则引起的，你不✓视频规则就能运行，或者用之前能运行的视频规则替换也能运行

**Comment by saoba1982** [comment]
请问以前的规则你还有么？

**Comment by jkle112** [comment]
所有的官方规则开启了，同时自己添加了不少规则，结果特别消耗内存，大概是规则文件的100倍。
通过重装系统修复了，但是对内存的消耗和运行高效，支持更多规则格式，都是需要官方更新的！

**Comment by rivernofish** [comment]
> 请问以前的规则你还有么？

https://raw.githubusercontent.com/project-lede/koolproxy/5d0134aa3ab9dfdb3dfb14d46a6d3441b982c2e1/rules/kp.dat

替换原文件，关闭自动更新

**Comment by michealhansun** [comment]
> > 请问以前的规则你还有么？
> 
> https://raw.githubusercontent.com/project-lede/koolproxy/5d0134aa3ab9dfdb3dfb14d46a6d3441b982c2e1/rules/kp.dat
> 
> 替换原文件，关闭自动更新

请问替换路径是哪里，没找到。。。

**Comment by michealhansun** [comment]
> > 请问以前的规则你还有么？
> 
> https://raw.githubusercontent.com/project-lede/koolproxy/5d0134aa3ab9dfdb3dfb14d46a6d3441b982c2e1/rules/kp.dat
> 
> 替换原文件，关闭自动更新

替换源文件了还是不行，有其它人成功吗

**Comment by dnpl** [comment]
替换后，关闭视频规则，可以正常运行，但是没有屏蔽广告的功能了

**Comment by rivernofish** [comment]
> 替换后，关闭视频规则，可以正常运行，但是没有屏蔽广告的功能了

你是5.4内核吗？我替换后是可以勾选视频规则的。

**Comment by dnpl** [comment]
> https://cloud.189.cn/web/share?code=ARj2YnbAZVRb

好的，谢谢，替换后已经可以正常运行，不知道后期能不能从根本解决问题，规则一直不敢更新。

**Comment by dnpl** [comment]
> > > 替换后，关闭视频规则，可以正常运行，但是没有屏蔽广告的功能了
> > 
> > 
> > 你是5.4内核吗？我替换后是可以勾选视频规则的。
> 
> 我重新刷了旧版本：内核版本 5.4.113 ，然后下载了3月份的规则，关闭更新，可以正常打开，正常过滤视频广告了，我规则我上传到天翼网盘：https://cloud.189.cn/web/share?code=ARj2YnbAZVRb
> 
> ![Image 2](https://user-images.githubusercontent.com/9845710/129288670-28d16f98-724b-4bfe-880b-49fc1cc41efd.jpg)



> > > 替换后，关闭视频规则，可以正常运行，但是没有屏蔽广告的功能了
> > 
> > 
> > 你是5.4内核吗？我替换后是可以勾选视频规则的。
> 
> 我重新刷了旧版本：内核版本 5.4.113 ，然后下载了3月份的规则，关闭更新，可以正常打开，正常过滤视频广告了，我规则我上传到天翼网盘：https://cloud.189.cn/web/share?code=ARj2YnbAZVRb
> 
> ![Image 2](https://user-images.githubusercontent.com/9845710/129288670-28d16f98-724b-4bfe-880b-49fc1cc41efd.jpg)

好的，谢谢，替换后已经可以正常运行，不知道后期能不能从根本解决问题，规则一直不敢更新。

**Comment by zubeeee** [comment]
自己修改kpupdate里面kp规则更新的地址或者直接注释掉或者删除掉,然后换正常的kp.dat 不影响其他规则正常更新

**Comment by jkle112** [comment]
> > > 请问以前的规则你还有么？
> > 
> > 
> > https://raw.githubusercontent.com/project-lede/koolproxy/5d0134aa3ab9dfdb3dfb14d46a6d3441b982c2e1/rules/kp.dat
> > 替换原文件，关闭自动更新
> 
> 替换源文件了还是不行，有其它人成功吗

替换后可以开启视频规则了，不过好景不长，今天早上点击更新规则，又停止运行，赶紧发测试版吧，多支持一些AdBlock plus的规则，我马上回去安装测试

**Comment by DanielEcho** [comment]
> > > > 请问以前的规则你还有么？
> > > 
> > > 
> > > https://raw.githubusercontent.com/project-lede/koolproxy/5d0134aa3ab9dfdb3dfb14d46a6d3441b982c2e1/rules/kp.dat
> > > 替换原文件，关闭自动更新
> > 
> > 
> > 替换源文件了还是不行，有其它人成功吗
> 
> 替换后可以开启视频规则了，不过好景不长，今天早上点击更新规则，又停止运行，仔细检查后，发现规则太多，内存都不够用了， 赶紧发测试版吧，优化内存使用，我可以添加更多的规则了，官方升级记得增加两个新规则。 多支持一些AdBlock plus的规则的话，用起来就起飞了，会成为所有固件的标配！ 希望可以尽快。迫切需要。

自己修改/usr/share/koolproxy/kpupdate文件
`update_rules() {
		 echo $(date "+%F %T"): ------------------- 内置规则更新 ------------------- >>$LOGFILE
	         wget 'https://raw.githubusercontent.com/michealhansun/godproxy-Rule/main/kp.dat' -q -O $KP_DIR/data/rules/kp.dat
            	 wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/daily.txt' -q -O $KP_DIR/data/rules/daily.txt
		 wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/koolproxy.txt' -q -O $KP_DIR/data/rules/koolproxy.txt
	         wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/yhosts.txt' -q -O $KP_DIR/data/rules/yhosts.txt
            	 wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/antiad.txt' -q -O $KP_DIR/data/rules/anti-ad.txt
            	 wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/mv.txt' -q -O $KP_DIR/data/rules/mv.txt
		 wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/ipsetadblock/koolproxy_ipset.conf' -q -O $KP_DIR/koolproxy_ipset.conf
		 wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/ipsetadblock/dnsmasq.adblock' -q -O $KP_DIR/dnsmasq.adblock
                 yhosts_rules_local=`cat /usr/share/koolproxy/data/rules/yhosts.txt  | sed -n '1p' | awk '{print $2,$3}'`
		 antiad_rules_local=`cat /usr/share/koolproxy/data/rules/anti-ad.txt  | sed -n '2p' | awk '{print $2,$3}'`
		 koolproxy_rules_local=`cat /usr/share/koolproxy/data/rules/koolproxy.txt  | sed -n '3p'|awk '{print $3,$4}'`
                 mv_rules_local=`cat /usr/share/koolproxy/data/rules/mv.txt  | sed -n '3p'|awk '{print $3,$4}'`
                 echo $(date "+%F %T"): -------------------ABP规则    Version $easylist_rules_local >>$LOGFILE
                 echo $(date "+%F %T"): -------------------Fanboy规则 Version $fanboy_rules_local >>$LOGFILE
		 echo $(date "+%F %T"): -------------------Yhosts规则 Version $yhosts_rules_local >>$LOGFILE
		 echo $(date "+%F %T"): -------------------Anti-AD规则 Version $antiad_rules_local >>$LOGFILE
		 echo $(date "+%F %T"): -------------------静态规则   Version $koolproxy_rules_local >>$LOGFILE
		 echo $(date "+%F %T"): -------------------乘风视频   Version $mv_rules_local >>$LOGFILE
                 echo $(date "+%F %T"): ------------------- 内置规则更新成功！ ------------------- >>$LOGFILE`

**Comment by project-lede** [comment]
猴子大大的规则内容已经为空了。所以无法识别。已经修复，最近实在忙，抱歉。
