### ISSUE TITLE
勾选视频规则后，插件显示未运行，不勾选则运行正常

### ISSUE THREAD

**Issue by Marcotso** [project-lede/luci-app-godproxy#42]
插件版本
luci-app-godproxy | 3.8.5-3-20210421
OP固件版本
OpenWrt R21.4.18 / LuCI Master (git-21.114.56541-974fb04)
内核5.4.121
日志如下：

Thu Aug 12 11:46:56 2021 daemon.info procd: Instance koolproxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Thu Aug 12 11:47:15 2021 user.notice root: koolproxy reload service.
Thu Aug 12 11:47:15 2021 user.notice root: koolproxy has stopped.
Thu Aug 12 11:47:15 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 11:47:15 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 11:47:15 2021 daemon.info dnsmasq[25007]: Connected to system UBus
Thu Aug 12 11:47:15 2021 user.notice root: koolproxy has started.
Thu Aug 12 11:47:15 2021 daemon.info koolproxy[25118]: koolproxy v3.8.5
Thu Aug 12 11:47:16 2021 daemon.err koolproxy[25118]: rule line=22128 not support ','
Thu Aug 12 11:47:16 2021 daemon.err koolproxy[25118]: rule line=22335 not support ','
Thu Aug 12 11:47:16 2021 daemon.err koolproxy[25118]: rule line=22990 not support ','
Thu Aug 12 11:47:16 2021 daemon.err koolproxy[25118]: rule line=28647 not support ','
Thu Aug 12 11:47:16 2021 daemon.err koolproxy[25118]: rule line=28854 not support ','
Thu Aug 12 11:47:16 2021 daemon.err koolproxy[25118]: rule line=29509 not support ','
Thu Aug 12 11:52:58 2021 user.notice root: koolproxy reload service.
Thu Aug 12 11:52:58 2021 user.notice root: koolproxy has stopped.
Thu Aug 12 11:52:58 2021 daemon.info dnsmasq[26313]: Connected to system UBus
Thu Aug 12 11:52:58 2021 user.notice root: koolproxy has started.
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: koolproxy v3.8.5
Thu Aug 12 11:52:58 2021 daemon.err koolproxy[26424]: Assertion failed: length >= 2 (/home/houzi-/develop/KoolProxy/src/adblock/adblock.c: rule_to_regex: 1000)
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: listen port=3000
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: log level=4
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: thread count=4
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: work path=/
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: program path=/usr/share/koolproxy/koolproxy
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: data path=/usr/share/koolproxy/data
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: ttl mode=160
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: ttl port=0
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: mark mode=1
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: max fd=131070
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: init adblock engine
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: load normal rule: /usr/share/koolproxy/data/rules/koolproxy.txt
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: load normal rule: /usr/share/koolproxy/data/rules/daily.txt
Thu Aug 12 11:52:58 2021 daemon.info koolproxy[26424]: load secret rule: /usr/share/koolproxy/data/rules/kp.dat

**Comment by zubeeee** [comment]
确实是的 正打算来反馈,发现已经有人反馈了,望解决

**Comment by brianzc0306** [comment]
不要反馈了作者也是拉别人得规则库

**Comment by louis000008** [comment]
应该是内置的视频规则地址坏了 github 上找了一个暂时可以  https://raw.githubusercontent.com/michealhansun/godproxy-Rule/main/kp.dat   规则订阅那填写下

**Comment by DanielEcho** [comment]
> 应该是内置的视频规则地址坏了 github 上找了一个暂时可以 https://raw.githubusercontent.com/michealhansun/godproxy-Rule/main/kp.dat 规则订阅那填写下

确实可以用。自己修改/usr/share/koolproxy/kpupdate文件

> `update_rules()` { echo $(date "+%F %T"): ------------------- 内置规则更新 ------------------- >>$LOGFILE wget 'https://raw.githubusercontent.com/michealhansun/godproxy-Rule/main/kp.dat' -q -O $KP_DIR/data/rules/kp.dat wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/daily.txt' -q -O $KP_DIR/data/rules/daily.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/koolproxy.txt' -q -O $KP_DIR/data/rules/koolproxy.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/yhosts.txt' -q -O $KP_DIR/data/rules/yhosts.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/antiad.txt' -q -O $KP_DIR/data/rules/anti-ad.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/mv.txt' -q -O $KP_DIR/data/rules/mv.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/ipsetadblock/koolproxy_ipset.conf' -q -O $KP_DIR/koolproxy_ipset.conf wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/ipsetadblock/dnsmasq.adblock' -q -O $KP_DIR/dnsmasq.adblock yhosts_rules_local=cat /usr/share/koolproxy/data/rules/yhosts.txt | sed -n '1p' | awk '{print $2,$3}' antiad_rules_local=cat /usr/share/koolproxy/data/rules/anti-ad.txt | sed -n '2p' | awk '{print $2,$3}' koolproxy_rules_local=cat /usr/share/koolproxy/data/rules/koolproxy.txt | sed -n '3p'|awk '{print $3,$4}' mv_rules_local=cat /usr/share/koolproxy/data/rules/mv.txt | sed -n '3p'|awk '{print $3,$4}' echo $(date "+%F %T"): -------------------ABP规则 Version $easylist_rules_local >>$LOGFILE echo $(date "+%F %T"): -------------------Fanboy规则 Version $fanboy_rules_local >>$LOGFILE echo $(date "+%F %T"): -------------------Yhosts规则 Version $yhosts_rules_local >>$LOGFILE echo $(date "+%F %T"): -------------------Anti-AD规则 Version $antiad_rules_local >>$LOGFILE echo $(date "+%F %T"): -------------------静态规则 Version $koolproxy_rules_local >>$LOGFILE echo $(date "+%F %T"): -------------------乘风视频 Version $mv_rules_local >>$LOGFILE echo $(date "+%F %T"): ------------------- 内置规则更新成功！ ------------------- >>$LOGFILE`

**Comment by gbeta** [comment]
替换后  视频规则显示是0

**Comment by palemoky** [comment]
同样的问题，我看视频规则的最后更新时间是2020-04-09，可能是失效的规则导致运行状态显示异常。
<img width="327" alt="video_rule" src="https://user-images.githubusercontent.com/21208635/136666741-aa7df7ff-3935-4341-9fe4-b8b72a317f3a.png">

我这里勾选视频规则后，同样会导致网络的问题，比如微信语音电话拨出提示呼叫失败，微博视频无法加载，小爱无法播放音乐等，取消视频规则的勾选才解决这些问题，希望作者可以默认去掉该规则，看来不少人掉坑里了

**Comment by Karmylr** [comment]
> 同样的问题，我看视频规则的最后更新时间是2020-04-09，可能是失效的规则导致运行状态显示异常。 <img alt="video_rule" width="327" src="https://user-images.githubusercontent.com/21208635/136666741-aa7df7ff-3935-4341-9fe4-b8b72a317f3a.png">
> 
> 我这里勾选视频规则后，同样会导致网络的问题，比如微信语音电话拨出提示呼叫失败，微博视频无法加载，小爱无法播放音乐等，取消视频规则的勾选才解决这些问题，希望作者可以默认去掉该规则，看来不少人掉坑里了

视频规则是猴子大大写的，没有任何问题，有问题的是这个插件。

**Comment by project-lede** [comment]
猴子大大的规则内容已经为空了。所以无法识别。已经修复，最近实在忙，抱歉。
