### ISSUE TITLE
无法更新规则，raw.sevencdn.com错误跳转到raw.githubusercontents.com而不是raw.githubusercontent.com

### ISSUE THREAD

**Issue by Portan** [project-lede/luci-app-godproxy#49]
现在更新规则老不成功，我查看了下，从raw.sevencdn.com下载规则会跳转到raw.githubusercontent**s**.com，实际上应该跳转到raw.githubusercontent.com，大佬能否修复下？
raw.githubusercontent**s**.com
raw.githubusercontent.com
多了个S，解析的IP就不对了

**Comment by project-lede** [comment]
已经@xiaoqi2020 等待他修复。
