### ISSUE TITLE
请求合并以下链接规则

### ISSUE THREAD

**Issue by ITdesk01** [project-lede/luci-app-godproxy#5]
HI project
你的插件很棒，我这里有个链接也麻烦合并一下，准确率挺不错的
http://sub.adtchrome.com/adt-chinalist-easylist.txt

**Comment by ITdesk01** [comment]
还有一个问题请教一次
测试自定义网站
https://www.right.com.cn/forum/forum.php
![image](https://user-images.githubusercontent.com/38835844/108475452-a9f0f300-72cb-11eb-90a9-ea0289e1ea70.png)


![image](https://user-images.githubusercontent.com/38835844/108475119-3f3fb780-72cb-11eb-9958-62caac0f7279.png)

我在自定义规则填写了这句过滤代码，但广告已经还是有，我已经保存和更新过规则，测试系统openwrt X86

**Comment by project-lede** [comment]
ABP规则

（ABP规则是CJX's Annoyance List+China+EasyList的二合一规则） 注：CJX's Annoyance List (反自我推广,移除anti adblock,防跟踪规则列表)是"EasyList China+EasyList" & "EasyPrivacy"的补充）

ABP已经包含了

**Comment by ITdesk01** [comment]
> ABP规则
> 
> （ABP规则是CJX's Annoyance List+China+EasyList的二合一规则） 注：CJX's Annoyance List (反自我推广,移除anti adblock,防跟踪规则列表)是"EasyList China+EasyList" & "EasyPrivacy"的补充）
> 
> ABP已经包含了

经过我的测试，插件自带的ABP规则，并不能过滤掉我图片网站的图片广告，但相反http://sub.adtchrome.com/adt-chinalist-easylist.txt这个可以过滤掉

网站地址是：https://www.right.com.cn/forum/forum.php

**Comment by project-lede** [comment]
我测试你的郭泽，是添加到自定义规则的，其余规则全部取消。会大致godproxy停止运行。你是在哪里测试的

**Comment by project-lede** [comment]
还有以前的godproxy规则地址被封了。今天更新了地址。你再试试。然后告诉我。

**Comment by ITdesk01** [comment]
> 还有以前的godproxy规则地址被封了。今天更新了地址。你再试试。然后告诉我。

我先试试最新地址如何，我的这个规则是在google浏览器插件上运行的，因为去除广告能力比较强，所以想能不能合并一下
这是插件地址
https://chrome.google.com/webstore/detail/%E5%B9%BF%E5%91%8A%E7%BB%88%E7%BB%93%E8%80%85/fpdnjdlbdmifoocedhkighhlbchbiikl

这是插件页面
![image](https://user-images.githubusercontent.com/38835844/109285171-b17c4300-785b-11eb-927b-cb4c8dbd785e.png)
![image](https://user-images.githubusercontent.com/38835844/109285189-b6d98d80-785b-11eb-90b2-de8fadc4f1dd.png)

**Comment by project-lede** [comment]
等下次coding挂了再说。

**Comment by project-lede** [comment]
已经修复，托管在github上

**Comment by ITdesk01** [comment]
> 已经修复，托管在github上

咨询一个问题，如图
![image](https://user-images.githubusercontent.com/38835844/109385193-0cca3600-792d-11eb-82ba-dc7c0a563e0c.png)

自定义规则，我这么写为什么屏蔽不了这个图片？？
||right.com.cn/forum/static/image/common/logo2.gif
