### ISSUE TITLE
关于最新规则更新问题以及临时解决办法。

### ISSUE THREAD

**Issue by project-lede** [project-lede/luci-app-godproxy#50]
实在很巧，昨天刚刚更新了下，就碰到sevencdn官方通告：
由于滥用，本服务已开启白名单，非白名单用户的请求将会转发至 GHUCS 服务。
您也可以试试 7ED 提供的 GHUCS 加速服务，通过 CLOUDFLARE CDN 提供无限制的加速服务，只需在 GITHUB RAW 源文件地址后加个 S 即可，即 RAW.GITHUBUSERCONTENTS.COM， 详情请访问 GHUCS 服务网站。

我已经申请白名单，请等待。如果通过就不用更新地址了，没有通过我在更新地址。

现在提供另外的地址：
自己修改/usr/share/koolproxy/kpupdate文件里的。将如下：
update_rules() { echo $(date "+%F %T"): ------------------- 内置规则更新 ------------------- >>$LOGFILE wget update_rules() 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/kp.dat' -q -O $KP_DIR/data/rules/kp.dat wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/daily.txt' -q -O $KP_DIR/data/rules/daily.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/koolproxy.txt' -q -O $KP_DIR/data/rules/koolproxy.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/yhosts.txt' -q -O $KP_DIR/data/rules/yhosts.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/antiad.txt' -q -O $KP_DIR/data/rules/anti-ad.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/rules/mv.txt' -q -O $KP_DIR/data/rules/mv.txt wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/ipsetadblock/koolproxy_ipset.conf' -q -O $KP_DIR/koolproxy_ipset.conf wget 'https://raw.sevencdn.com/project-lede/koolproxy/main/ipsetadblock/dnsmasq.adblock' -

将https://raw.sevencdn.com/project-lede/koolproxy/main   替换为 https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master  即可。例子：
update_rules() { echo $(date "+%F %T"): ------------------- 内置规则更新 ------------------- >>$LOGFILE wget 'https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master/rules/kp.dat' -q -O $KP_DIR/data/rules/kp.dat wget 'https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master/rules/daily.txt' -q -O $KP_DIR/data/rules/daily.txt wget 'https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master/rules/koolproxy.txt' -q -O $KP_DIR/data/rules/koolproxy.txt wget 'https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master/rules/yhosts.txt' -q -O $KP_DIR/data/rules/yhosts.txt wget 'https://cdn.jsdelivr.net/gh/project-lede/koolproxy@masterrules/antiad.txt' -q -O $KP_DIR/data/rules/anti-ad.txt wget 'https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master/rules/mv.txt' -q -O $KP_DIR/data/rules/mv.txt wget 'https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master/ipsetadblock/koolproxy_ipset.conf' -q -O $KP_DIR/koolproxy_ipset.conf wget 'https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master/ipsetadblock/dnsmasq.adblock' -

测试是否有效：在浏览器输入  https://cdn.jsdelivr.net/gh/project-lede/koolproxy@master/rules/mv.txt   看看是否看到乘风 视频广告过滤规则。

**Comment by project-lede** [comment]
等两天如果没有通过sevencdn的白名单，就更新为以上地址。大家等等等

**Comment by Portan** [comment]
大佬，kpupdate这个文件，127行是不是多了一个“ ` ”
![image](https://user-images.githubusercontent.com/19484691/140600562-67b78d1c-bd26-4f71-8e58-c8dd9771c6c2.png)

**Comment by project-lede** [comment]
已更新正

**Comment by Beginner-Go** [comment]
为什么回退

**Comment by project-lede** [comment]
无法编译。这次砍得厉害了

**Comment by Beginner-Go** [comment]
那是我漏写了一行代码导致的，麻烦赶紧git reset

**Comment by project-lede** [comment]
新建了x86分支，你在x86分支上修建。main分支不要动了。

**Comment by Beginner-Go** [comment]
> 新建了x86分支，你在x86分支上修建。main分支不要动了。

你有tg吗？

**Comment by Beginner-Go** [comment]
插件改名就在这个号改吧，没必要再换号
