### ISSUE TITLE
证书管理出错

### ISSUE THREAD

**Issue by Portan** [project-lede/luci-app-godproxy#58]
新装的godproxy, 点击导出证书时出错。好像https去广告功能也不正常
![image](https://user-images.githubusercontent.com/19484691/141326454-33a11f99-2a7f-4599-b6ff-a105e0fbcb7a.png)

**Comment by Beginner-Go** [comment]
我有空看看

**Comment by Beginner-Go** [comment]
应该是原代码历史遗留问题，我想了个另类办法处理了

**Comment by Portan** [comment]
solved
