### ISSUE TITLE
11月13日更新后勾选Fanboy规则会导致GodProxy不能正常运行

### ISSUE THREAD

**Issue by pbx168** [project-lede/luci-app-godproxy#64]
勾选Fanboy规则后，GodProxy不能正常运行，不断切换显示GodProxy 滤广告运行中和GodProxy 滤广告停止运行，在全局模式下会导致设备不能联网。不勾选Fanboy规则才能正常显示GodProxy 滤广告运行中。

**Comment by project-lede** [comment]
昨晚刚刚升级了规则。你再更新试试

**Comment by pbx168** [comment]
> 昨晚刚刚升级了上游abp和fanboy规则。你再更新试试

手动更新了之后连ABP规则都不能用，ABP和fanboy这两个规则只要勾选就不能运行了，不知道其他人有没有问题？我14号那天编译完使用是没有问题的，因为设置了早上5点自动更新规则，所以今天早上就发现出问题了，应该是跟昨晚上游abp和fanboy这两个规则升级有关？

**Comment by pbx168** [comment]
> 昨晚刚刚升级了上游abp和fanboy规则。你再更新试试

我把abp和fanboy规则的规则下载下来对比了一下，发现这两个规则出现了大量的重复，应该是大量重复导致冲突了。

**Comment by project-lede** [comment]
你下载来的是估计是缓存。新版本是catsteam的。

**Comment by nnttm1122** [comment]
今天中午我也发现不能正常运行，去掉ABP就可以了，我本身不需要用Fanboy，所以没在意勾选Fanboy是否有影响，改用的Anti-AD了，使用暂时正常

**Comment by project-lede** [comment]
antaid和yhosts，没有问题，而且效果明显。abp和fanboy基本是摆设，所以昨天开始才处理这两个规则。今天采用catsteam的，并做了优化。不过我后台更新还是缓存。没有更新到最新文件。

**Comment by project-lede** [comment]
升级18日版本
