### ISSUE TITLE
11月18日更新后勾选Fanboy或者ABP规则会导致GodProxy不能正常运行，乘风视频规则无法更新。

### ISSUE THREAD

**Issue by alexliu269** [project-lede/luci-app-godproxy#65]
更新到18日版本，ABP和Fanboy任意勾选其中一个或者同时勾选，会出现不能正常运行的情况，乘风视频规则无法更新。

**Comment by alexliu269** [comment]
更新完最新的规则以后 开启ABP 和 fanboy插件可以正常运行了 勾选Abp后 京东 ios app 无法正常使用 出现无网络和图片无法打开的情况 关闭abp后正常

**Comment by project-lede** [comment]
abp和fanboy规则好像没有什么效果。下个版本要提出了。换成其他规则。
