### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by project-lede** [project-lede/luci-app-godproxy#66]
一直提示无法运行。规则是没有问题的。我在老版本上运行没有问题。今天升级到了最新。一直无法运行。 @Beginner-Go

**Comment by Beginner-Go** [comment]
是不保存配置升级的固件？

**Comment by Beginner-Go** [comment]
我这边测过了 没有问题

**Comment by Beginner-Go** [comment]
![kpr](https://user-images.githubusercontent.com/70857188/142909160-102190b0-0c1e-4208-9649-55bb43cb9fca.png)

实测在5.10内核运行没有问题

**Comment by project-lede** [comment]
不知道是我编译出问题了。现在编译出来是2个文件一个是koolproxy的ipk另外一个是luci。先安装koolproxy在装luci就是不行。把你编译好的ipk给我一份。860573311@qq.com

**Comment by Beginner-Go** [comment]
不玩qq, 只玩tg

**Comment by dnpl** [comment]
> 不知道是我编译出问题了。现在编译出来是2个文件一个是koolproxy的ipk另外一个是luci。先安装koolproxy在装luci就是不行。把你编译好的ipk给我一份。[860573311@qq.com](mailto:860573311@qq.com)。 @Beginner-Go

我跟你的情况一样，也是安装后无法运行

**Comment by Beginner-Go** [comment]
大多数自己的问题，建议不保存配置随固件刷入。

**Comment by project-lede** [comment]
再次编译还是出问题。luci_app出来只有17kb大小。以前老版本出来要500多kb。应该是没有带进二进制文件。 
 @Beginner-Go

**Comment by Beginner-Go** [comment]
luci和二进制是拆分的

**Comment by Beginner-Go** [comment]
正常编译有2个ipk

**Comment by project-lede** [comment]
是的。一个koolproxy的ipk，另外一个luci。先装第一个，再装第二个。删除原来的配置文件以及koolproxy文件夹，就是安装不上去。晚点我再试试。

**Comment by dnpl** [comment]
> 是的。一个koolproxy的ipk，另外一个luci。先装第一个，再装第二个。删除原来的配置文件以及koolproxy文件夹，就是安装不上去。晚点我再试试。

我也一样，编译出来的插件如图所示，也能安装上，就是运行不了。
![image](https://user-images.githubusercontent.com/22452022/143357286-d5209773-e060-457d-b656-5a9fbb551473.png)

**Comment by dnpl** [comment]
> 正常编译有2个ipk

能否释放出一个编译好的release 版本让我们测试一下

**Comment by Beginner-Go** [comment]
最好把你的tg发一下，我远程看看

**Comment by dnpl** [comment]
> 最好把你的tg发一下，我远程看看
我的是界面打不开
![image](https://user-images.githubusercontent.com/22452022/143365755-28770fc7-6bb2-46fc-968a-4d3d5b4fcff6.png)

**Comment by iwrt** [comment]
看来只有随固件编译的才好用。单独在固件上安装，需要安装好依赖。已经更名了。 @Beginner-Go

**Comment by Beginner-Go** [comment]
> 看来只有随固件编译的才好用。单独在固件上安装，需要安装好依赖。已经更名了。 @Beginner-Go

建议二进制Makefile 不要改包名

**Comment by iwrt** [comment]
@Beginner-Go  已加

**Comment by Beginner-Go** [comment]
已整理，需要重新clone后编译

**Comment by iwrt** [comment]
和以前的KPR以及KPR Plus还有+，都不兼容。意思是你要么彻底删除以前的，要么重刷一个没有KoolProxy的固件，再新安装ikoolproxy。
