### ISSUE TITLE
无法更新订阅规则

### ISSUE THREAD

**Issue by ghaner** [project-lede/luci-app-godproxy#68]
如图
![ilNML5Qufu](https://user-images.githubusercontent.com/51288907/143003669-0227b5b5-3f6e-4ac1-b3bc-df739fe771bf.png)
![qcLTzzJy9T](https://user-images.githubusercontent.com/51288907/143003678-1ab5de2e-05ff-48e3-a421-27bb19402f8a.png)

**Comment by project-lede** [comment]
你这个不是最新版本。#67

**Comment by ghaner** [comment]
> 你这个不是最新版本。最新版是这个 [user-images.githubusercontent.com/70857188/142909160-102190b0-0c1e-4208-9649-55bb43cb9fca.png](https://user-images.githubusercontent.com/70857188/142909160-102190b0-0c1e-4208-9649-55bb43cb9fca.png)

谢谢,已经重新刷新固件编译最新版本的软件,仍然提示"获取在线版本时出现错误! "
![XjcS8VzZ88](https://user-images.githubusercontent.com/51288907/143144436-4c28e126-647e-40c3-8902-780068d33560.png)

**Comment by project-lede** [comment]
你在仔细检查下，应该没有问题。再更新下规则看看。难道规则地址挂了？

**Comment by ghaner** [comment]
问题仍然存在,检查不出哪里出了问题,请高手解惑.谢谢
